project_id = "wnkifmuhkhdjbswraini"

[functions.process-edp-llamaparse]
verify_jwt = false

[functions.ingest-enqueue]
verify_jwt = false

[functions.ingest-worker]
verify_jwt = false

[functions.verify-contract]
verify_jwt = false
