project_id = "wnkifmuhkhdjbswraini"

[functions.ingest-enqueue]
verify_jwt = false

[functions.ingest-worker]
verify_jwt = false
schedule = "* * * * *"

[functions.verify-contract]
verify_jwt = false
